server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itmo_lab2
    username: root
    password: testtest
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    user: root
    password: testtest
    default-schema: itmo_lab2
    locations: classpath:db/migration
    schemas: itmo_lab2
    url: jdbc:mysql://localhost:3306/itmo_lab2

logging:
  level:
    root: INFO