server:
  port: 8081

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/itmo_tech
    username: postgres
    password: testtest
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

